# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from draw import Draw
from algorithms import * 
from settingsDialog import settingsDialog

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1111, 1015)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Canvas = Draw(parent=self.centralwidget)
        self.Canvas.setObjectName("Canvas")
        self.horizontalLayout.addWidget(self.Canvas)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1111, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAnalysis = QtWidgets.QMenu(parent=self.menubar)
        self.menuAnalysis.setObjectName("menuAnalysis")
        self.menuView = QtWidgets.QMenu(parent=self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuClear = QtWidgets.QMenu(parent=self.menubar)
        self.menuClear.setObjectName("menuClear")
        self.menuSettings = QtWidgets.QMenu(parent=self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actionOpen = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icons/open_file.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtGui.QAction(parent=MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/icons/exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionExit.setIcon(icon1)
        self.actionExit.setObjectName("actionExit")
        self.actionCreate_DT = QtGui.QAction(parent=MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/icons/triangles2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionCreate_DT.setIcon(icon2)
        self.actionCreate_DT.setObjectName("actionCreate_DT")
        self.actionCreateContouLines = QtGui.QAction(parent=MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/icons/contours2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionCreateContouLines.setIcon(icon3)
        self.actionCreateContouLines.setObjectName("actionCreateContouLines")
        self.actionAnalyzeSlope = QtGui.QAction(parent=MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/icons/slope2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionAnalyzeSlope.setIcon(icon4)
        self.actionAnalyzeSlope.setObjectName("actionAnalyzeSlope")
        self.actionAnalyzeExposition = QtGui.QAction(parent=MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/icons/orientation2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionAnalyzeExposition.setIcon(icon5)
        self.actionAnalyzeExposition.setObjectName("actionAnalyzeExposition")
        self.actionDT = QtGui.QAction(parent=MainWindow)
        self.actionDT.setCheckable(True)
        self.actionDT.setObjectName("actionDT")
        self.actionContour_lines_2 = QtGui.QAction(parent=MainWindow)
        self.actionContour_lines_2.setCheckable(True)
        self.actionContour_lines_2.setObjectName("actionContour_lines_2")
        self.actionSlope = QtGui.QAction(parent=MainWindow)
        self.actionSlope.setCheckable(True)
        self.actionSlope.setObjectName("actionSlope")
        self.actionExposition = QtGui.QAction(parent=MainWindow)
        self.actionExposition.setCheckable(True)
        self.actionExposition.setObjectName("actionExposition")
        self.actionClear_results = QtGui.QAction(parent=MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/icons/clear.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionClear_results.setIcon(icon6)
        self.actionClear_results.setObjectName("actionClear_results")
        self.actionClear_all = QtGui.QAction(parent=MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/icons/clear_all.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionClear_all.setIcon(icon7)
        self.actionClear_all.setObjectName("actionClear_all")
        self.actionParameters = QtGui.QAction(parent=MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("images/icons/settings.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionParameters.setIcon(icon8)
        self.actionParameters.setObjectName("actionParameters")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuAnalysis.addAction(self.actionCreate_DT)
        self.menuAnalysis.addSeparator()
        self.menuAnalysis.addAction(self.actionCreateContouLines)
        self.menuAnalysis.addAction(self.actionAnalyzeSlope)
        self.menuAnalysis.addAction(self.actionAnalyzeExposition)
        self.menuView.addAction(self.actionDT)
        self.menuView.addAction(self.actionContour_lines_2)
        self.menuView.addAction(self.actionSlope)
        self.menuView.addAction(self.actionExposition)
        self.menuClear.addAction(self.actionClear_results)
        self.menuClear.addSeparator()
        self.menuClear.addAction(self.actionClear_all)
        self.menuSettings.addAction(self.actionParameters)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuClear.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCreate_DT)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCreateContouLines)
        self.toolBar.addAction(self.actionAnalyzeSlope)
        self.toolBar.addAction(self.actionAnalyzeExposition)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClear_results)
        self.toolBar.addAction(self.actionClear_all)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionParameters)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)
        
        # Open text file
        self.actionOpen.triggered.connect(self.openTextFileClick)
        
        # Default parameters for contour lines
        self.dz = 20.0
        self.z_min = 0.0
        self.z_max = 1500.0

        self.actionParameters.triggered.connect(self.openSettingsClick)
        
        # Connects
        self.actionCreate_DT.triggered.connect(self.createDTClick)
        self.actionCreateContouLines.triggered.connect(self.createContourLinesClick)
        
        self.actionAnalyzeSlope.triggered.connect(self.createSlopeClick)
        self.actionAnalyzeExposition.triggered.connect(self.createAspectClick)
        
        self.actionDT.triggered.connect(self.Canvas.setShowDT)
        self.actionContour_lines_2.triggered.connect(self.Canvas.setShowContours)
        self.actionSlope.triggered.connect(self.Canvas.setShowSlope)
        self.actionExposition.triggered.connect(self.Canvas.setShowAspect)
        
        self.actionClear_results.triggered.connect(self.Canvas.clearResult)
        self.actionClear_all.triggered.connect(self.Canvas.clearAll)
        self.actionExit.triggered.connect(MainWindow.close)
        
        self.Canvas.setZRange(self.z_min, self.z_max)

        self.retranslateUi(MainWindow)
    
    def openTextFileClick(self):
        # Open text file with 3D points
        file_path, _ = QFileDialog.getOpenFileName(self.centralwidget, "Otevřít body terénu", "", "Text files (*.txt *.xyz *.csv);;All files (*)")
        
        if file_path:            
            points_3d = []
            
            # Load points from file
            with open(file_path, 'r') as f:
                for line in f:
                    parts = line.replace(',', ' ').split() 
                    
                    # Expecting lines with at least 3 values (x, y, z)
                    if len(parts) >= 3:
                        try:
                            x, y, z = float(parts[0]), float(parts[1]), float(parts[2])
                            points_3d.append((x, y, z))
                        except ValueError:
                            continue
                            
            if not points_3d:
                return

            # Calculate bounding box of the points
            min_x = min(p[0] for p in points_3d)
            max_x = max(p[0] for p in points_3d)
            min_y = min(p[1] for p in points_3d)
            max_y = max(p[1] for p in points_3d)
            
            w_world = max_x - min_x
            h_world = max_y - min_y
            
            # Canvas size
            canvas_w = self.Canvas.width()
            canvas_h = self.Canvas.height()
            
            # Calculate scale
            scale_x = canvas_w / w_world if w_world > 0 else 1
            scale_y = canvas_h / h_world if h_world > 0 else 1
            scale = min(scale_x, scale_y) * 0.8
            
            # Calculate center of the world coordinates
            cx_world = (min_x + max_x) / 2
            cy_world = (min_y + max_y) / 2
            
            points_list = []
            
            # Transform world coordinates to screen coordinates
            for x, y, z in points_3d:
                screen_x = (x - cx_world) * scale + (canvas_w / 2)
                screen_y = -(y - cy_world) * scale + (canvas_h / 2)
                
                points_list.append(QPoint3DF(screen_x, screen_y, z))
            
            # Rendering
            self.Canvas.clearResult()
            self.Canvas.getPoints().clear()
            self.Canvas.getPoints().extend(points_list)
            self.Canvas.repaint()
            
            self.pixel_to_meter = 1 / scale
    
    def openSettingsClick(self):
        # Open settings dialog
        dialog = settingsDialog(self.dz, self.z_min, self.z_max)
        if dialog.exec():
            self.dz, self.z_min, self.z_max = dialog.get_values()
            
        self.Canvas.setZRange(self.z_min, self.z_max)
        
    def createDTClick(self):        
        # Get points
        points = self.Canvas.getPoints()
        
        # Create new object
        a = Algorithms()
        
        # Create DT
        dt = a.createDT(points)
        
        # Set results
        self.Canvas.setDT(dt)
        
        self.Canvas.setShowDT(True)
        self.actionDT.setChecked(True)
        
        self.Canvas.repaint()
        
    def createContourLinesClick(self):
            # Create contour lines
            DT = self.Canvas.getDT()
            
            # We need to create DT
            if len(DT) <3:
                self.createDTClick()
                DT = self.Canvas.getDT()
                
            # Use parameters from settings
            z_min = int(self.z_min)
            z_max = int(self.z_max)
            dz = int(self.dz)
            dz_main = 100

            # Create contour lines
            a = Algorithms()
            contours = a.createContourLines(DT, z_min, z_max, dz)
            main_contours = a.createContourLines(DT, z_min, z_max, dz_main)
            
            labels = a.getContourLabels(main_contours)
            self.Canvas.setLabels(labels)

            # Set results
            self.Canvas.setContours(contours)
            self.Canvas.setMainContours(main_contours)
            
            self.Canvas.setShowContours(True)
            self.actionContour_lines_2.setChecked(True)
            
            self.Canvas.repaint()
        
    def createSlopeClick(self):
        # Analyze slope
        DT = self.Canvas.getDT()
        
        if len(DT) < 3:
            self.createDTClick()
            DT = self.Canvas.getDT()
        
        # If there is no pixel_to_meter conversion factor
        if not hasattr(self, 'pixel_to_meter'):
            self.pixel_to_meter = 1.0
            
        a = Algorithms()
        slope_triangles = a.analyzeSlope(DT, self.pixel_to_meter)
        
        self.Canvas.setSlopeTriangles(slope_triangles)
        self.Canvas.setShowSlope(True)
        self.Canvas.setShowAspect(False)
        
        self.actionSlope.setChecked(True)  
        self.actionExposition.setChecked(False)
        
        self.Canvas.repaint()
        
    def createAspectClick(self):
        # Analyze aspect
        DT = self.Canvas.getDT()
        
        if len(DT) < 3:
            self.createDTClick()
            DT = self.Canvas.getDT()
        
        a = Algorithms()
        aspect_triangles = a.analyzeAspect(DT)
        
        self.Canvas.setAspectTriangles(aspect_triangles)
        
        self.Canvas.setShowAspect(True)
        self.Canvas.setShowSlope(False)
        
        self.actionExposition.setChecked(True)
        self.actionSlope.setChecked(False)
        
        self.Canvas.repaint()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DTM Analysis"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAnalysis.setTitle(_translate("MainWindow", "Analysis"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuClear.setTitle(_translate("MainWindow", "Clear"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setToolTip(_translate("MainWindow", "Open file"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setToolTip(_translate("MainWindow", "Exit application"))
        self.actionExit.setShortcut(_translate("MainWindow", "Backspace"))
        self.actionCreate_DT.setText(_translate("MainWindow", "Create DT"))
        self.actionCreate_DT.setToolTip(_translate("MainWindow", "Create Delaunay triangulation"))
        self.actionCreateContouLines.setText(_translate("MainWindow", "Create contour lines"))
        self.actionAnalyzeSlope.setText(_translate("MainWindow", "Analyze slope"))
        self.actionAnalyzeSlope.setToolTip(_translate("MainWindow", "Analyze DTM slope"))
        self.actionAnalyzeExposition.setText(_translate("MainWindow", "Analyze exposition"))
        self.actionAnalyzeExposition.setToolTip(_translate("MainWindow", "Analyze DTM exposition"))
        self.actionDT.setText(_translate("MainWindow", "DT"))
        self.actionContour_lines_2.setText(_translate("MainWindow", "Contour lines"))
        self.actionSlope.setText(_translate("MainWindow", "Slope"))
        self.actionExposition.setText(_translate("MainWindow", "Exposition"))
        self.actionClear_results.setText(_translate("MainWindow", "Clear results"))
        self.actionClear_all.setText(_translate("MainWindow", "Clear all"))
        self.actionParameters.setText(_translate("MainWindow", "Parameters"))
from draw import Draw

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())